language: nix
install:
- nix-channel --add https://nixos.org/channels/nixos-18.03 nixpkgs
- nix-channel --update
script:
- nix-build
- ./result/bin/site clean
- ./result/bin/site build
env:
  matrix:
    secure: K5fq+ih59ng1ivF6uPMyb0vXeOQppwLrBI487KPQMsqThqIQAwAx6a52+R0Fb1jYxd7KSlRBpGjO4bvXVUqgS+t8KvN2NhMPBEn15TT/vnFQTQSjo5c7DTLgvYWQ4pJBWtJeyis+OJBEiV06tWy1OpOqg/G8TvepJrvtOxOTvexbDdUAGWm5n1eIJWCVyczbKyPOGZdrHnHC4ILqaKQbLu60uDSSdnVjGHtvZ70snzeBFAY922GXFwQpsuGvLzh+O6krBVOGCE6VAawNdu3QtN6gNt7dfG0bov+UVdzlvCD6OAhxYgAZ/iwIly1wIUvI1Qmy4RYRuJj4aMQRL7OgsfEx4DDKSCQ+/9YRbEDw5gACkJiddep3ze6QKsQEEAm9LopiByPiYAp2T4SdsFENGygsXlmxP+l05RrmS9JFSQNvkoHKRNOfED0uho2FBnd2Ke0MiJClTCEez9yqDKqGWjoHG4rBNPCaVxGtO4TFv+xcRWuNzsi+lxeLe2RWPhC5CJOYP+24QbJhVfM0wQnd3LiKZ1twdka25KCEgvf3nF6vSyCTvy+sdCl9UM1zH9o/2qh5RJoKOLMLwlxGi9QcItpyPckBK4Nn/nEs73BKhNIAygkH5gkh4p3k2A6mmXgNW8ffGkxfjrgmot8E3nfVBS3MmdMw/KZwsO7ScIB6fRo=
deploy:
  provider: pages
  local-dir: _site
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
