name:                blog
version:             1.3.0
github:              "kaizhang91/blog"
license:             BSD3
author:              "Kai Zhang"
maintainer:          "kaizhang91@foxmail.com"
copyright:           "Kai Zhang"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/kaizhang91/blog#readme>

dependencies:
- base >= 4.7 && < 5
- hakyll >= 4.12
- hakyll-sass >= 0.2
- pandoc >= 2.2
- pandoc-citeproc >= 0.14
- pandoc-crossref >= 0.3
- pandoc-types >= 1.17

library:
  source-dirs: src

executables:
  blog:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog

tests:
  blog-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - blog
